# K means clustering
On MNIST Dataset

Problem:
Implement the **K − means** algorithm. Your program must accept as input an d × N data matrix X, the number of clusters K, and the stopping threshold e. Your program must output the following:
* the error at the end of each iteration,
* the K centroids at convergence,
* the K clusters at convergence.

You are encouraged to draw inputs X from realistic scenarios. For example, you could use a color image and  luster the pixels based on their color. For such an example, you can display the clusters by assigning unique colors to each of them.
> Note: Python 3 is used.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv

In [3]:
class Kmeans():
    def __init__(self, img_path, K=3):
        self.K = K
        self.img = cv.cvtColor(cv.imread(img_path, cv.IMREAD_COLOR), cv.COLOR_BGR2RGB)
        self.img_shape = self.img.shape
        self.x = np.reshape(self.img, (self.img.shape[0]*self.img.shape[1], 3))
        pixels = np.unique(self.x, axis=0)
        self.means = pixels[np.random.choice(len(pixels), self.K, replace=False)]
    
    # update the means and calculate error
    def update(self):
        self.new_means = []
        self.assign_k = np.array([np.argmin(np.array([np.linalg.norm(pix-mean) for mean in self.means])) for pix in self.x])
        for k in np.arange(self.K):
            kth_cluster = self.x[np.argwhere(self.assign_k==k).flatten()]
            self.new_means.append(np.mean(kth_cluster, axis=0))
            
        self.error = np.linalg.norm(self.new_means - self.means)
        return np.array(self.new_means)
    
    # cluster the pixels by updating the means till error < ε 
    def cluster(self,e):
        count = 0 # initial iteration
        self.means = self.update()
        print('Iteration count = ', count, '  -->  Error = ', self.error)
        count += 1
        while(self.error > e): # interations untill error < ε 
            self.means = self.update()
            print('Iteration count = ', count, '  -->  Error = ', self.error)
            count += 1
        print('Done')
    
    # print the means and clusters at convergence
    def get_clusters(self): 
        print('MEANS at covergence: ' , self.means)
        for k in range(self.K): 
            kth_cluster = self.x[np.argwhere(self.assign_k==k).flatten()]
            print('Cluster ', k+1, ' : ', kth_cluster)
            
    # pixel belonging to each cluster is show by the color of the centroid of the cluster
    def show_clusters(self):
        cluster_img = self.means[self.assign_k].astype(np.int).reshape(self.img_shape)
        fig = plt.figure(figsize=self.img_shape[:2])
        fig.add_subplot(1,2,1) # show original image
        plt.imshow(self.img)
        fig.add_subplot(1,2,2) # show clusters
        plt.imshow(cluster_img)
        plt.show()

In [7]:
classfier = Kmeans(img_path='chess.png', K=2)
classfier.cluster(0.001)
classfier.get_clusters()
classfier.show_clusters()

Iteration count =  0   -->  Error =  265.83131379564657
Iteration count =  1   -->  Error =  244.30230711132145
Iteration count =  2   -->  Error =  0.49002188076974756
Iteration count =  3   -->  Error =  0.0
Done
MEANS at covergence:  [[ 28.06686454  28.06686454  28.06686454]
 [250.41680055 250.41680055 250.41680055]]
Cluster  1  :  [[131 131 131]
 [131 131 131]
 [ 98  98  98]
 ...
 [110 110 110]
 [131 131 131]
 [134 134 134]]
Cluster  2  :  [[254 254 254]
 [254 254 254]
 [255 255 255]
 ...
 [254 254 254]
 [254 254 254]
 [254 254 254]]


In [8]:
classfier = Kmeans(img_path='spidey.jpeg', K=3)
classfier.cluster(0.1)
classfier.get_clusters()
classfier.show_clusters()

Iteration count =  0   -->  Error =  179.47821820824
Iteration count =  1   -->  Error =  129.70271083563406
Iteration count =  2   -->  Error =  7.615632033884037
Iteration count =  3   -->  Error =  2.9941927127884513
Iteration count =  4   -->  Error =  1.0597918949209242
Iteration count =  5   -->  Error =  0.531499687410925
Iteration count =  6   -->  Error =  0.18448712441080561
Iteration count =  7   -->  Error =  0.07305362225657253
Done
MEANS at covergence:  [[ 68.30450614  46.74112426  62.3279472 ]
 [181.37731497  55.21131538  55.89905705]
 [252.07619898 251.41794099 251.21453287]]
Cluster  1  :  [[125  22  23]
 [122  31  30]
 [116  46  46]
 ...
 [ 66  76  68]
 [ 83  94  86]
 [109 122 113]]
Cluster  2  :  [[198 153 156]
 [196 151 154]
 [195 150 153]
 ...
 [152 151 147]
 [141 140 136]
 [139 155 145]]
Cluster  3  :  [[255 255 255]
 [255 255 255]
 [255 255 255]
 ...
 [255 255 255]
 [255 255 255]
 [255 255 255]]


In [9]:
classfier = Kmeans(img_path='colors.jpg', K=3)
classfier.cluster(1.0)
classfier.get_clusters()
classfier.show_clusters()

Iteration count =  0   -->  Error =  192.6314319237358
Iteration count =  1   -->  Error =  101.65731219231687
Iteration count =  2   -->  Error =  24.44983857899719
Iteration count =  3   -->  Error =  6.629525943290065
Iteration count =  4   -->  Error =  2.9540328477734485
Iteration count =  5   -->  Error =  0.8684998124577922
Done
MEANS at covergence:  [[209.61194906 103.6125239   32.84438224]
 [ 73.69136751  39.60341877 152.39216371]
 [ 39.90968678 184.20064863 148.66774772]]
Cluster  1  :  [[195  61  62]
 [198  59  54]
 [197  59  57]
 ...
 [225 143  15]
 [217 139  13]
 [171 153  29]]
Cluster  2  :  [[ 35  91 142]
 [ 37  93 154]
 [ 37  97 160]
 ...
 [ 31  76 159]
 [ 32  77 160]
 [ 32  77 160]]
Cluster  3  :  [[ 36 157  90]
 [ 33 161  87]
 [ 37 158  91]
 ...
 [  1 140 147]
 [  0 142 146]
 [  3 125 149]]


In [4]:
classfier = Kmeans(img_path='colors.jpg', K=10)
classfier.cluster(0.1)
classfier.get_clusters()
classfier.show_clusters()

Iteration count =  0   -->  Error =  453.5825712631051
Iteration count =  1   -->  Error =  124.41599883003809
Iteration count =  2   -->  Error =  73.42373046038567
Iteration count =  3   -->  Error =  52.24280570901844
Iteration count =  4   -->  Error =  20.45452068779895
Iteration count =  5   -->  Error =  17.797449719587938
Iteration count =  6   -->  Error =  24.32611344438412
Iteration count =  7   -->  Error =  23.001601460507686
Iteration count =  8   -->  Error =  17.4820781896558
Iteration count =  9   -->  Error =  3.4933675134834323
Iteration count =  10   -->  Error =  1.8054366154971717
Iteration count =  11   -->  Error =  0.9491368860219493
Iteration count =  12   -->  Error =  0.7122329222039796
Iteration count =  13   -->  Error =  0.4027971030823049
Iteration count =  14   -->  Error =  0.20610411616775218
Iteration count =  15   -->  Error =  0.057939945222682615
Done
MEANS at covergence:  [[212.73984588 110.75541821  24.1409536 ]
 [ 63.72337682  27.97797948 107.5