# Neural Network

Implement the back-propagation algorithm to learn the weights of a perceptron with 2 input nodes, 2 hidden nodes and 1 output node.

Note: **Python3** in used.

## AND 

In [40]:
# imports
import numpy as np

In [63]:
# parameters - input all parameter values here
input_dim = 2
hidden_dim = 2 # dimensions of hidden layers
std = 0.01  # train data noise standard deviation
w_std = 0.3
learn_rate = 0.01

In [64]:
# prepare training data
x_inputs = np.array([np.zeros(2), np.ones(2), np.array([1,0]), np.array([0,1])])
def generate_trainset(N):
    X = np.repeat(x_inputs, N//4, axis=0)
    y_xor = np.logical_xor(X.T[0], X.T[1]).astype(np.float)
    # add noise to data
    X += np.random.normal(0, std, X.shape)
    y_xor += np.random.normal(0, std, N)
    # shuffle the training data
    indices = np.arange(N)
    np.random.shuffle(indices)
    x_train, y_train = X[indices], y_xor[indices]
    return x_train, y_train

In [65]:
def sigmoid( t):
    return 1/(1  + np.exp(-t))

def dsigmoid( t):
    return sigmoid(t)*(1 - sigmoid(t))

######  Experiment with N = 1000

In [66]:
N = 1000
x_train, y_train = generate_trainset(N)

In [67]:
# initialize weights
A  = np.random.normal(0, w_std, (hidden_dim, input_dim))
a0 = np.random.normal(0, w_std, hidden_dim)
b0 = np.random.normal(0, w_std, 1)
B  = np.random.normal(0, w_std, hidden_dim)
epochs = 300 # number of itrations\
# training def predict(x_test):
    results =  [sigmoid(np.dot(B, sigmoid(np.dot(A, x)+a0)) + b0) for x in x_test]
    return np.array(results)
def decision(x_test):
    return (predict(x_test) > 0.5).astype(int)
print(predict(x_inputs))
print(decision(x_inputs))
for epoch in range(epochs):
    dSSE_a, dSSE_b, z_bias, y_bias = np.zeros_like(A), np.zeros_like(B), np.zeros_like(B), 0
    loss = 0
    for i, x in enumerate(x_train):
        z = sigmoid(np.dot(A,x)+a0)
        y_hat = sigmoid(np.dot(B,z)+b0)
        y_error = y_hat - y_train[i]
        y_delta = 2* y_error * dsigmoid(np.dot(B, z) + b0)
        s = dsigmoid(np.dot(A,x) + a0) * B * y_delta
        # print(s.shape)
        dSSE_b += y_delta*z
        dSSE_a += np.tensordot(s,x, axes=0)
        # print(dSSE_a.shape)
        y_bias += y_delta
        z_bias += s
        loss += y_error**2

    A  = A - learn_rate * dSSE_a
    B  = B - learn_rate * dSSE_b
    a0 = a0 - learn_rate * s
    b0 = b0 - learn_rate * y_delta

    print('Epoch: ', str(epoch+1) + '/'+str(epochs), ' Loss: ', loss/N)   

Epoch:  1/300  Loss:  [0.25105842]
Epoch:  2/300  Loss:  [0.25026549]
Epoch:  3/300  Loss:  [0.25018358]
Epoch:  4/300  Loss:  [0.2501714]
Epoch:  5/300  Loss:  [0.25016727]
Epoch:  6/300  Loss:  [0.25016445]
Epoch:  7/300  Loss:  [0.25016199]
Epoch:  8/300  Loss:  [0.25015966]
Epoch:  9/300  Loss:  [0.25015743]
Epoch:  10/300  Loss:  [0.25015528]
Epoch:  11/300  Loss:  [0.25015318]
Epoch:  12/300  Loss:  [0.25015115]
Epoch:  13/300  Loss:  [0.25014916]
Epoch:  14/300  Loss:  [0.25014723]
Epoch:  15/300  Loss:  [0.25014534]
Epoch:  16/300  Loss:  [0.25014349]
Epoch:  17/300  Loss:  [0.25014169]
Epoch:  18/300  Loss:  [0.25013992]
Epoch:  19/300  Loss:  [0.25013818]
Epoch:  20/300  Loss:  [0.25013647]
Epoch:  21/300  Loss:  [0.25013479]
Epoch:  22/300  Loss:  [0.25013314]
Epoch:  23/300  Loss:  [0.25013152]
Epoch:  24/300  Loss:  [0.25012991]
Epoch:  25/300  Loss:  [0.25012833]
Epoch:  26/300  Loss:  [0.25012677]
Epoch:  27/300  Loss:  [0.25012522]
Epoch:  28/300  Loss:  [0.25012369]
Ep

Epoch:  227/300  Loss:  [0.14085244]
Epoch:  228/300  Loss:  [0.13997129]
Epoch:  229/300  Loss:  [0.13911257]
Epoch:  230/300  Loss:  [0.13827539]
Epoch:  231/300  Loss:  [0.13745891]
Epoch:  232/300  Loss:  [0.1366623]
Epoch:  233/300  Loss:  [0.13588479]
Epoch:  234/300  Loss:  [0.13512561]
Epoch:  235/300  Loss:  [0.13438404]
Epoch:  236/300  Loss:  [0.13365939]
Epoch:  237/300  Loss:  [0.13295099]
Epoch:  238/300  Loss:  [0.1322582]
Epoch:  239/300  Loss:  [0.13158043]
Epoch:  240/300  Loss:  [0.13091709]
Epoch:  241/300  Loss:  [0.13026763]
Epoch:  242/300  Loss:  [0.12963153]
Epoch:  243/300  Loss:  [0.1290083]
Epoch:  244/300  Loss:  [0.12839746]
Epoch:  245/300  Loss:  [0.12779855]
Epoch:  246/300  Loss:  [0.12721116]
Epoch:  247/300  Loss:  [0.12663487]
Epoch:  248/300  Loss:  [0.12606929]
Epoch:  249/300  Loss:  [0.12551406]
Epoch:  250/300  Loss:  [0.12496883]
Epoch:  251/300  Loss:  [0.12443326]
Epoch:  252/300  Loss:  [0.12390703]
Epoch:  253/300  Loss:  [0.12338984]
Epoc

In [68]:
def predict(x_test):
    results =  [sigmoid(np.dot(B, sigmoid(np.dot(A, x)+a0)) + b0) for x in x_test]
    return np.array(results)
def decision(x_test):
    return (predict(x_test) > 0.5).astype(int)
print(predict(x_inputs))
print(decision(x_inputs))

[[0.12423437]
 [0.50977433]
 [0.72896377]
 [0.73034588]]
[[0]
 [1]
 [1]
 [1]]


######  Experiment with N = 100

In [69]:
N = 100
x_train, y_train = generate_trainset(N)

In [70]:
# initialize weights
A  = np.random.normal(0, w_std, (hidden_dim, input_dim))
a0 = np.random.normal(0, w_std, hidden_dim)
b0 = np.random.normal(0, w_std, 1)
B  = np.random.normal(0, w_std, hidden_dim)
epochs = 500 # number of itrations
for epoch in range(epochs):
    dSSE_a, dSSE_b, z_bias, y_bias = np.zeros_like(A), np.zeros_like(B), np.zeros_like(B), 0
    loss = 0
    for i, x in enumerate(x_train):
        z = sigmoid(np.dot(A,x)+a0)
        y_hat = sigmoid(np.dot(B,z)+b0)
        y_error = y_hat - y_train[i]
        y_delta = 2* y_error * dsigmoid(np.dot(B, z) + b0)
        s = dsigmoid(np.dot(A,x) + a0) * B * y_delta
        # print(s.shape)
        dSSE_b += y_delta*z
        dSSE_a += np.tensordot(s,x, axes=0)
        # print(dSSE_a.shape)
        y_bias += y_delta
        z_bias += s
        loss += y_error**2

    A  = A - learn_rate * dSSE_a
    B  = B - learn_rate * dSSE_b
    a0 = a0 - learn_rate * s
    b0 = b0 - learn_rate * y_delta

    print('Epoch: ', str(epoch+1) + '/'+str(epochs), ' Loss: ', loss/N)   

Epoch:  1/500  Loss:  [0.25902529]
Epoch:  2/500  Loss:  [0.25820643]
Epoch:  3/500  Loss:  [0.25745343]
Epoch:  4/500  Loss:  [0.25676196]
Epoch:  5/500  Loss:  [0.25612787]
Epoch:  6/500  Loss:  [0.2555472]
Epoch:  7/500  Loss:  [0.25501614]
Epoch:  8/500  Loss:  [0.2545311]
Epoch:  9/500  Loss:  [0.25408867]
Epoch:  10/500  Loss:  [0.25368561]
Epoch:  11/500  Loss:  [0.2533189]
Epoch:  12/500  Loss:  [0.25298567]
Epoch:  13/500  Loss:  [0.25268326]
Epoch:  14/500  Loss:  [0.25240917]
Epoch:  15/500  Loss:  [0.25216107]
Epoch:  16/500  Loss:  [0.25193679]
Epoch:  17/500  Loss:  [0.25173432]
Epoch:  18/500  Loss:  [0.25155178]
Epoch:  19/500  Loss:  [0.25138745]
Epoch:  20/500  Loss:  [0.25123974]
Epoch:  21/500  Loss:  [0.25110717]
Epoch:  22/500  Loss:  [0.25098838]
Epoch:  23/500  Loss:  [0.25088212]
Epoch:  24/500  Loss:  [0.25078725]
Epoch:  25/500  Loss:  [0.25070271]
Epoch:  26/500  Loss:  [0.25062755]
Epoch:  27/500  Loss:  [0.25056087]
Epoch:  28/500  Loss:  [0.25050186]
Epoc

Epoch:  242/500  Loss:  [0.25074105]
Epoch:  243/500  Loss:  [0.25074353]
Epoch:  244/500  Loss:  [0.25074598]
Epoch:  245/500  Loss:  [0.25074842]
Epoch:  246/500  Loss:  [0.25075084]
Epoch:  247/500  Loss:  [0.25075325]
Epoch:  248/500  Loss:  [0.25075564]
Epoch:  249/500  Loss:  [0.25075801]
Epoch:  250/500  Loss:  [0.25076036]
Epoch:  251/500  Loss:  [0.25076269]
Epoch:  252/500  Loss:  [0.250765]
Epoch:  253/500  Loss:  [0.25076729]
Epoch:  254/500  Loss:  [0.25076957]
Epoch:  255/500  Loss:  [0.25077182]
Epoch:  256/500  Loss:  [0.25077406]
Epoch:  257/500  Loss:  [0.25077627]
Epoch:  258/500  Loss:  [0.25077847]
Epoch:  259/500  Loss:  [0.25078064]
Epoch:  260/500  Loss:  [0.25078279]
Epoch:  261/500  Loss:  [0.25078492]
Epoch:  262/500  Loss:  [0.25078703]
Epoch:  263/500  Loss:  [0.25078912]
Epoch:  264/500  Loss:  [0.25079118]
Epoch:  265/500  Loss:  [0.25079323]
Epoch:  266/500  Loss:  [0.25079525]
Epoch:  267/500  Loss:  [0.25079725]
Epoch:  268/500  Loss:  [0.25079922]
Epo

Epoch:  480/500  Loss:  [0.25072393]
Epoch:  481/500  Loss:  [0.25072232]
Epoch:  482/500  Loss:  [0.2507207]
Epoch:  483/500  Loss:  [0.25071909]
Epoch:  484/500  Loss:  [0.25071748]
Epoch:  485/500  Loss:  [0.25071587]
Epoch:  486/500  Loss:  [0.25071426]
Epoch:  487/500  Loss:  [0.25071266]
Epoch:  488/500  Loss:  [0.25071106]
Epoch:  489/500  Loss:  [0.25070946]
Epoch:  490/500  Loss:  [0.25070787]
Epoch:  491/500  Loss:  [0.25070627]
Epoch:  492/500  Loss:  [0.25070469]
Epoch:  493/500  Loss:  [0.2507031]
Epoch:  494/500  Loss:  [0.25070152]
Epoch:  495/500  Loss:  [0.25069994]
Epoch:  496/500  Loss:  [0.25069837]
Epoch:  497/500  Loss:  [0.2506968]
Epoch:  498/500  Loss:  [0.25069524]
Epoch:  499/500  Loss:  [0.25069368]
Epoch:  500/500  Loss:  [0.25069213]


In [71]:
def predict(x_test):
    results =  [sigmoid(np.dot(B, sigmoid(np.dot(A, x)+a0)) + b0) for x in x_test]
    return np.array(results)
def decision(x_test):
    return (predict(x_test) > 0.5).astype(int)
print(predict(x_inputs))
print(decision(x_inputs))

[[0.48967783]
 [0.48596564]
 [0.48581156]
 [0.48905856]]
[[0]
 [0]
 [0]
 [0]]
