# Neural Network

Implement the back-propagation algorithm to learn the weights of a perceptron with 2 input nodes, 2 hidden nodes and 1 output node.

Note: **Python3** in used.

## AND 

In [47]:
# imports
import numpy as np

In [48]:
# parameters - input all parameter values here
input_dim = 2
hidden_dim = 2 # dimensions of hidden layers
std = 0.01  # train data noise standard deviation
w_std = 1
learn_rate = 0.01

In [49]:
# prepare training data
x_inputs = np.array([np.zeros(2), np.ones(2), np.array([1,0]), np.array([0,1])])
def generate_trainset(N):
    X = np.repeat(x_inputs, N//4, axis=0)
    y_and = np.logical_and(X.T[0], X.T[1]).astype(np.float)
    # add noise to data
    X += np.random.normal(0, std, X.shape)
    y_and += np.random.normal(0, std, N)
    # shuffle the training data
    indices = np.arange(N)
    np.random.shuffle(indices)
    x_train, y_train = X[indices], y_and[indices]
    return x_train, y_train

In [50]:
def sigmoid( t):
    return 1/(1  + np.exp(-t))

def dsigmoid( t):
    return sigmoid(t)*(1 - sigmoid(t))

######  Experiment with N = 1000

In [51]:
N = 1000
x_train, y_train = generate_trainset(N)

In [52]:
# initialize weights
A  = np.random.normal(0, w_std, (hidden_dim, input_dim))
a0 = np.random.normal(0, w_std, hidden_dim)
b0 = np.random.normal(0, w_std, 1)
B  = np.random.normal(0, w_std, hidden_dim)
epochs = 300 # number of itrations\
# training 005
for epoch in range(epochs):
    dSSE_a, dSSE_b, z_bias, y_bias = np.zeros_like(A), np.zeros_like(B), np.zeros_like(B), 0
    loss = 0
    for i, x in enumerate(x_train):
        z = sigmoid(np.dot(A,x)+a0)
        y_hat = sigmoid(np.dot(B,z)+b0)
        y_error = y_hat - y_train[i]
        y_delta = 2* y_error * dsigmoid(np.dot(B, z) + b0)
        s = dsigmoid(np.dot(A,x) + a0) * B * y_delta
        # print(s.shape)
        dSSE_b += y_delta*z
        dSSE_a += np.tensordot(s,x, axes=0)
        # print(dSSE_a.shape)
        y_bias += y_delta
        z_bias += s
        loss += y_error**2

    A  = A - learn_rate * dSSE_a
    B  = B - learn_rate * dSSE_b
    a0 = a0 - learn_rate * s
    b0 = b0 - learn_rate * y_delta

    print('Epoch: ', str(epoch+1) + '/'+str(epochs), ' Loss: ', loss/N)   

Epoch:  1/300  Loss:  [0.35316205]
Epoch:  2/300  Loss:  [0.3065292]
Epoch:  3/300  Loss:  [0.26516439]
Epoch:  4/300  Loss:  [0.23015027]
Epoch:  5/300  Loss:  [0.2026048]
Epoch:  6/300  Loss:  [0.18259133]
Epoch:  7/300  Loss:  [0.16827796]
Epoch:  8/300  Loss:  [0.15717554]
Epoch:  9/300  Loss:  [0.14771514]
Epoch:  10/300  Loss:  [0.1392497]
Epoch:  11/300  Loss:  [0.13152086]
Epoch:  12/300  Loss:  [0.12439547]
Epoch:  13/300  Loss:  [0.1177938]
Epoch:  14/300  Loss:  [0.11166927]
Epoch:  15/300  Loss:  [0.10599634]
Epoch:  16/300  Loss:  [0.10076012]
Epoch:  17/300  Loss:  [0.09594842]
Epoch:  18/300  Loss:  [0.09154691]
Epoch:  19/300  Loss:  [0.08753701]
Epoch:  20/300  Loss:  [0.08389583]
Epoch:  21/300  Loss:  [0.08059723]
Epoch:  22/300  Loss:  [0.07761319]
Epoch:  23/300  Loss:  [0.07491523]
Epoch:  24/300  Loss:  [0.0724755]
Epoch:  25/300  Loss:  [0.07026758]
Epoch:  26/300  Loss:  [0.06826694]
Epoch:  27/300  Loss:  [0.06645119]
Epoch:  28/300  Loss:  [0.06480012]
Epoch:

Epoch:  266/300  Loss:  [0.03806939]
Epoch:  267/300  Loss:  [0.03806286]
Epoch:  268/300  Loss:  [0.03805639]
Epoch:  269/300  Loss:  [0.03804996]
Epoch:  270/300  Loss:  [0.03804359]
Epoch:  271/300  Loss:  [0.03803727]
Epoch:  272/300  Loss:  [0.03803099]
Epoch:  273/300  Loss:  [0.03802477]
Epoch:  274/300  Loss:  [0.03801859]
Epoch:  275/300  Loss:  [0.03801246]
Epoch:  276/300  Loss:  [0.03800638]
Epoch:  277/300  Loss:  [0.03800035]
Epoch:  278/300  Loss:  [0.03799436]
Epoch:  279/300  Loss:  [0.03798842]
Epoch:  280/300  Loss:  [0.03798252]
Epoch:  281/300  Loss:  [0.03797667]
Epoch:  282/300  Loss:  [0.03797086]
Epoch:  283/300  Loss:  [0.0379651]
Epoch:  284/300  Loss:  [0.03795937]
Epoch:  285/300  Loss:  [0.03795369]
Epoch:  286/300  Loss:  [0.03794806]
Epoch:  287/300  Loss:  [0.03794246]
Epoch:  288/300  Loss:  [0.03793691]
Epoch:  289/300  Loss:  [0.0379314]
Epoch:  290/300  Loss:  [0.03792592]
Epoch:  291/300  Loss:  [0.03792049]
Epoch:  292/300  Loss:  [0.0379151]
Epoc

In [53]:
0.5def predict(x_test):
    results =  [sigmoid(np.dot(B, sigmoid(np.dot(A, x)+a0)) + b0) for x in x_test]
    return np.array(results)
def decision(x_test):
    return (predict(x_test) > 0.5).astype(int)
print(predict(x_inputs))
print(decision(x_inputs))

[[0.03417009]
 [0.61430546]
 [0.02584656]
 [0.02229733]]
[[0]
 [1]
 [0]
 [0]]


######  Experiment with N = 100

In [54]:
N = 100
x_train, y_train = generate_trainset(N)

In [55]:
# initialize weights
A  = np.random.normal(0, w_std, (hidden_dim, input_dim))
a0 = np.random.normal(0, w_std, hidden_dim)
b0 = np.random.normal(0, w_std, 1)
B  = np.random.normal(0, w_std, hidden_dim)
epochs = 500 # number of itrations
for epoch in range(epochs):
    dSSE_a, dSSE_b, z_bias, y_bias = np.zeros_like(A), np.zeros_like(B), np.zeros_like(B), 0
    loss = 0
    for i, x in enumerate(x_train):
        z = sigmoid(np.dot(A,x)+a0)
        y_hat = sigmoid(np.dot(B,z)+b0)
        y_error = y_hat - y_train[i]
        y_delta = 2* y_error * dsigmoid(np.dot(B, z) + b0)
        s = dsigmoid(np.dot(A,x) + a0) * B * y_delta
        # print(s.shape)
        dSSE_b += y_delta*z
        dSSE_a += np.tensordot(s,x, axes=0)
        # print(dSSE_a.shape)
        y_bias += y_delta
        z_bias += s
        loss += y_error**2

    A  = A - learn_rate * dSSE_a
    B  = B - learn_rate * dSSE_b
    a0 = a0 - learn_rate * s
    b0 = b0 - learn_rate * y_delta

    print('Epoch: ', str(epoch+1) + '/'+str(epochs), ' Loss: ', loss/N)   

Epoch:  1/500  Loss:  [0.33929734]
Epoch:  2/500  Loss:  [0.31741866]
Epoch:  3/500  Loss:  [0.29743375]
Epoch:  4/500  Loss:  [0.27959469]
Epoch:  5/500  Loss:  [0.26398834]
Epoch:  6/500  Loss:  [0.2505601]
Epoch:  7/500  Loss:  [0.23915367]
Epoch:  8/500  Loss:  [0.22955362]
Epoch:  9/500  Loss:  [0.22152155]
Epoch:  10/500  Loss:  [0.21482182]
Epoch:  11/500  Loss:  [0.20923701]
Epoch:  12/500  Loss:  [0.20457549]
Epoch:  13/500  Loss:  [0.20067334]
Epoch:  14/500  Loss:  [0.19739326]
Epoch:  15/500  Loss:  [0.19462175]
Epoch:  16/500  Loss:  [0.19226584]
Epoch:  17/500  Loss:  [0.19024974]
Epoch:  18/500  Loss:  [0.18851181]
Epoch:  19/500  Loss:  [0.18700197]
Epoch:  20/500  Loss:  [0.18567949]
Epoch:  21/500  Loss:  [0.18451119]
Epoch:  22/500  Loss:  [0.18346998]
Epoch:  23/500  Loss:  [0.18253365]
Epoch:  24/500  Loss:  [0.18168398]
Epoch:  25/500  Loss:  [0.18090591]
Epoch:  26/500  Loss:  [0.180187]
Epoch:  27/500  Loss:  [0.17951691]
Epoch:  28/500  Loss:  [0.17888701]
Epoc

Epoch:  226/500  Loss:  [0.10975055]
Epoch:  227/500  Loss:  [0.1096838]
Epoch:  228/500  Loss:  [0.10961777]
Epoch:  229/500  Loss:  [0.10955246]
Epoch:  230/500  Loss:  [0.10948786]
Epoch:  231/500  Loss:  [0.10942396]
Epoch:  232/500  Loss:  [0.10936074]
Epoch:  233/500  Loss:  [0.10929819]
Epoch:  234/500  Loss:  [0.10923631]
Epoch:  235/500  Loss:  [0.10917507]
Epoch:  236/500  Loss:  [0.10911448]
Epoch:  237/500  Loss:  [0.10905452]
Epoch:  238/500  Loss:  [0.10899518]
Epoch:  239/500  Loss:  [0.10893644]
Epoch:  240/500  Loss:  [0.10887831]
Epoch:  241/500  Loss:  [0.10882078]
Epoch:  242/500  Loss:  [0.10876382]
Epoch:  243/500  Loss:  [0.10870744]
Epoch:  244/500  Loss:  [0.10865162]
Epoch:  245/500  Loss:  [0.10859636]
Epoch:  246/500  Loss:  [0.10854164]
Epoch:  247/500  Loss:  [0.10848746]
Epoch:  248/500  Loss:  [0.10843382]
Epoch:  249/500  Loss:  [0.1083807]
Epoch:  250/500  Loss:  [0.10832809]
Epoch:  251/500  Loss:  [0.10827599]
Epoch:  252/500  Loss:  [0.10822438]
Epo

Epoch:  465/500  Loss:  [0.10252959]
Epoch:  466/500  Loss:  [0.10251384]
Epoch:  467/500  Loss:  [0.10249813]
Epoch:  468/500  Loss:  [0.10248246]
Epoch:  469/500  Loss:  [0.10246683]
Epoch:  470/500  Loss:  [0.10245125]
Epoch:  471/500  Loss:  [0.1024357]
Epoch:  472/500  Loss:  [0.1024202]
Epoch:  473/500  Loss:  [0.10240473]
Epoch:  474/500  Loss:  [0.10238931]
Epoch:  475/500  Loss:  [0.10237392]
Epoch:  476/500  Loss:  [0.10235857]
Epoch:  477/500  Loss:  [0.10234327]
Epoch:  478/500  Loss:  [0.10232799]
Epoch:  479/500  Loss:  [0.10231276]
Epoch:  480/500  Loss:  [0.10229757]
Epoch:  481/500  Loss:  [0.10228241]
Epoch:  482/500  Loss:  [0.10226729]
Epoch:  483/500  Loss:  [0.10225221]
Epoch:  484/500  Loss:  [0.10223716]
Epoch:  485/500  Loss:  [0.10222215]
Epoch:  486/500  Loss:  [0.10220718]
Epoch:  487/500  Loss:  [0.10219224]
Epoch:  488/500  Loss:  [0.10217734]
Epoch:  489/500  Loss:  [0.10216247]
Epoch:  490/500  Loss:  [0.10214764]
Epoch:  491/500  Loss:  [0.10213284]
Epo

In [56]:
def predict(x_test):
    results =  [sigmoid(np.dot(B, sigmoid(np.dot(A, x)+a0)) + b0) for x in x_test]
    return np.array(results)
def decision(x_test):
    return (predict(x_test) > 0.5).astype(int)
print(predict(x_inputs))
print(decision(x_inputs))

[[0.01345305]
 [0.39295303]
 [0.13775548]
 [0.15107429]]
[[0]
 [0]
 [0]
 [0]]
